name: Node.js CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests found"

      - name: Build Docker image
        run: docker build -t nodejs-cicd-demo:latest .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 nodejs-cicd-demo:latest
